### PR TITLE
Fix issue - ProblemDetails Content-Type incorrect when using ProducesAttribute

### LINKED ISSUE #137: Incorrect Content-Type on Problem responses if using ProducesAttribute and NotFoundObjectResult
Steps to reproduce:

1. In aspnetcore 3.1 web api project, add Hellang.Middleware.ProblemDetails nuget reference, wire up services and middleware in Startup.cs
2. Annotate an Api Controller with ProducesAttribute and multiple content types, e.g. `[Produces("application/hal+json", "application/problem+json")]`
3. Add logic to a Controller action such that a `NotFoundObjectResult` with a string value is returned.  e.g. via the ControllerBase.NotFound(object value) helper method
4. Start the web app and send a request to the action to trigger the NotFoundResult.  Inspect response Content-Type header, it will be the first content type passed to the ProducesAttribute rather than application/problem+json

I think the issue may be due to [line 96](https://github.com/khellang/Middleware/blob/e89e45aafa7f71f6474b37c24134b785551edf09/src/ProblemDetails/Mvc/ProblemDetailsResultFilter.cs#L96) of `ProblemDetailsResultFilter`, which assigns ProblemDetailsOptions.ContentTypes to an ObjectResult.ContentTypes whereas it probably should be copying the contents of the collection across to a new MediaTypeCollection instance instead (because ProducesAttribute calls ObjectResult.ContentTypes.Clear())

If I pin it down while coding a workaround I'll be happy to submit a PR to fix, thanks

### PR DESCRIPTION
**Pull request by TU-OB-GW**
Resolves #137 
(Incorrect Content-Type when using ProducesAttribute, ProblemDetailsResultFilter and ObjectResult with Status >= 400)

- Edit `ProblemDetailsResultFilter.Order` to be greater than the default of zero used by ProducesAttribute. This avoids ProducesAttribute resetting ObjectResult.ContentTypes
- `MediaTypeCollectionExtensions.Clone` extension method added to be used when assigning ContentTypes to an ObjectResult, to avoid ProblemDetailsOptions.ContentTypes being accidentally edited

### CODE REVIEW

File: src/ProblemDetails/ProblemDetailsOptions.cs [hunk 1]
```diff
@@ -121,7 +121,7 @@ public ProblemDetailsOptions()
         /// Gets the supported <c>Content-Type</c> values for use in content negotiation.
         /// The default values are <c>application/problem+json</c> and <c>application/problem+xml</c>.
         /// </summary>
-        public MediaTypeCollection ContentTypes { get; }
+        public IList<MediaTypeHeaderValue> ContentTypes { get; }
```
Comment (TU-OB-GW) [inline src/ProblemDetails/ProblemDetailsOptions.cs:124]: just realised this is a bad idea as it's a breaking change - existing code calling ContentTypes.Add(string) will fail to compile which isn't ideal (although it would force users to supply valid media types)

perhaps IList<string> would be better, although that would break existing code that calls ContentTypes.Add(MediaTypeHeaderValue)...

Comment (khellang) [reply src/ProblemDetails/ProblemDetailsOptions.cs:124]: Yeah, it's really a bug that we just assign the existing (mutable) options collection and not a copy, but I'd like to revert the breaking changes and just make sure we do a clone/copy when assigning 😊

Comment (TU-OB-GW) [reply src/ProblemDetails/ProblemDetailsOptions.cs:124]: sure thing, do you want the ProblemDetailsResultFilter.Order change on it's own separate PR?

File: src/ProblemDetails/ProblemDetailsOptions.cs [hunk 2]
```diff
@@ -2,7 +2,6 @@
 using System.Collections.Generic;
 using System.Diagnostics;
 using Microsoft.AspNetCore.Http;
-using Microsoft.AspNetCore.Mvc;
```
Comment (TU-OB-GW) [inline src/ProblemDetails/ProblemDetailsOptions.cs:5]: ??

Comment (TU-OB-GW) [reply src/ProblemDetails/ProblemDetailsOptions.cs:5]: obvs wasn't used, as the build has passed

**Comment by khellang** [comment]
Thanks for this! ❤️

**Comment by khellang** [comment]
Pushed 5.4.1 to NuGet :)

**Comment by TU-OB-GW** [comment]
> Thanks for this! ❤️

no problemo - thanks for producing and maintaining such a useful library.  The problem related code I inherited before switching to this was awful in comparison!
